CREATE TABLE `ecchatrecords` (
  `pk` varchar(32) NOT NULL,
  `chat_duration` int(11) DEFAULT NULL,
  `chat_end_time` datetime DEFAULT NULL,
  `chat_start_time` datetime DEFAULT NULL,
  `chat_type` varchar(255) DEFAULT NULL,
  `company_pk` varchar(100) DEFAULT NULL,
  `delete_ip` varchar(255) DEFAULT NULL,
  `delete_pk` varchar(255) DEFAULT NULL,
  `delete_time` datetime DEFAULT NULL,
  `department_pk` varchar(255) DEFAULT NULL,
  `exit_type` varchar(255) DEFAULT NULL,
  `insert_ip` varchar(255) DEFAULT NULL,
  `insert_pk` varchar(255) DEFAULT NULL,
  `insert_time` datetime DEFAULT NULL,
  `is_delete` int(11) DEFAULT NULL,
  `is_satisfaction` int(11) DEFAULT NULL,
  `isqc` int(11) DEFAULT NULL,
  `keyword_pk` varchar(255) DEFAULT NULL,
  `member_id` varchar(255) DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  `msg_content` text,
  `operator_conversations` int(11) DEFAULT NULL,
  `operator_pk` varchar(255) DEFAULT NULL,
  `option_pk` varchar(255) DEFAULT NULL,
  `queue_end_time` datetime DEFAULT NULL,
  `queue_start_time` datetime DEFAULT NULL,
  `referrerurl_pk` varchar(255) DEFAULT NULL,
  `request_time` datetime DEFAULT NULL,
  `response_end_time` datetime DEFAULT NULL,
  `response_start_time` datetime DEFAULT NULL,
  `satisfaction_memo` varchar(255) DEFAULT NULL,
  `satisfaction_pk` varchar(255) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `score_name` varchar(255) DEFAULT NULL,
  `score_time` datetime DEFAULT NULL,
  `searchengine_pk` varchar(255) DEFAULT NULL,
  `speed_response` bigint(20) DEFAULT NULL,
  `speed_response_num` int(11) DEFAULT NULL,
  `topic_memo` varchar(1000) DEFAULT NULL,
  `topic_names` varchar(255) DEFAULT NULL,
  `topic_pks` varchar(255) DEFAULT NULL,
  `trench` varchar(255) DEFAULT NULL,
  `update_ip` varchar(255) DEFAULT NULL,
  `update_pk` varchar(255) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `user_source` varchar(255) DEFAULT NULL,
  `version` bigint(20) DEFAULT NULL,
  `visitor_id` varchar(100) DEFAULT NULL,
  `visitor_ip` varchar(255) DEFAULT NULL,
  `visitor_ip_code` varchar(11) DEFAULT NULL,
  `visitor_ip_name` varchar(255) DEFAULT NULL,
  `visitor_name` varchar(255) DEFAULT NULL,
  `visters_conversations` int(11) DEFAULT NULL,
  `voice_score` int(11) DEFAULT '0',
  `topic_Type` varchar(255) DEFAULT NULL,
  `next_satisfaction_pk` varchar(255) DEFAULT NULL,
  `wx_callback_url` varchar(255) DEFAULT NULL,
  `event_name` varchar(1000) DEFAULT NULL,
  `event_target_name` varchar(1000) DEFAULT NULL,
  `from_page` varchar(255) DEFAULT NULL,
  `from_title` varchar(255) DEFAULT NULL,
  `is_allot` int(11) DEFAULT NULL,
  `companyname` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `FK66291C8C86B73C5D` (`department_pk`) USING BTREE,
  KEY `IDX_COMPANY_PK` (`company_pk`) USING BTREE,
  KEY `IDX_COMPANY_PK_AND_REQUEST_TIME` (`company_pk`,`request_time`) USING BTREE,
  KEY `IDX_OPERATOR_PK` (`operator_pk`) USING BTREE,
  KEY `IDX_VISITOR_NAME` (`visitor_name`) USING BTREE,
  KEY `IDX_CHAT_TIME` (`chat_start_time`,`chat_end_time`,`request_time`) USING BTREE,
  KEY `IDX_COMPANY_PK_AND_VISITOR_ID` (`company_pk`,`visitor_id`) USING BTREE,
  KEY `IDX_VISITOR_ID_AND_CHAT_START_TIME` (`visitor_id`,`chat_start_time`,`company_pk`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

 CREATE TABLE `ecchatfaqcorpus` (
  `QUESTION` varchar(256) NOT NULL,
  `ANSWER` varchar(1024) NOT NULL,
  `TIME` datetime NOT NULL,
  `FAQID` int(11) NOT NULL,
  `COMPANY_PK` varchar(32) NOT NULL,
  `COHERENCE` double NOT NULL,
  `ORIGIN` int(8) DEFAULT NULL,
  `RESPONDENT` varchar(32) DEFAULT NULL,
  `FREQUENCY` double DEFAULT '2'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ecchatreportunknownquestion` (
  `COMPANY_PK` varchar(32) COLLATE utf8_bin NOT NULL,
  `TIME` datetime DEFAULT NULL,
  `QUESTION` varchar(2048) COLLATE utf8_bin NOT NULL,
  `ANSWER` varchar(2048) COLLATE utf8_bin DEFAULT NULL,
  `COHERENCE` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `eccommonstored` (
  `pk` varchar(32) NOT NULL,
  `companypk` varchar(255) DEFAULT NULL,
  `deleteip` varchar(255) DEFAULT NULL,
  `deletepk` varchar(255) DEFAULT NULL,
  `deletetime` datetime DEFAULT NULL,
  `insertip` varchar(255) DEFAULT NULL,
  `insertpk` varchar(255) DEFAULT NULL,
  `inserttime` datetime DEFAULT NULL,
  `isdelete` int(11) DEFAULT NULL,
  `updateip` varchar(255) DEFAULT NULL,
  `updatepk` varchar(255) DEFAULT NULL,
  `updatetime` datetime DEFAULT NULL,
  `version` bigint(20) NOT NULL,
  `content` varchar(600) DEFAULT NULL,
  `operatorpk` varchar(255) DEFAULT NULL,
  `parentpk` varchar(255) DEFAULT NULL,
  `storefiletype` int(11) DEFAULT NULL,
  `storetype` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`pk`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `eccompany` (
  `PK` varchar(32) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `VERSION` decimal(65,0) DEFAULT NULL,
  `DELETEIP` varchar(20) DEFAULT NULL,
  `DELETEPK` varchar(32) DEFAULT NULL,
  `DELETETIME` datetime DEFAULT NULL,
  `INSERTIP` varchar(20) DEFAULT NULL,
  `INSERTPK` varchar(32) DEFAULT NULL,
  `INSERTTIME` datetime DEFAULT NULL,
  `UPDATEIP` varchar(20) DEFAULT NULL,
  `UPDATEPK` varchar(32) DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `ISDELETE` decimal(2,0) DEFAULT NULL,
  `ADDRESS` varchar(200) DEFAULT NULL COMMENT '公司地址',
  `REMARKS` text COMMENT '公司备注',
  `EXT1` varchar(255) DEFAULT NULL COMMENT '在线客服',
  `EXT2` varchar(255) DEFAULT NULL COMMENT '登录CODE',
  `EXT3` varchar(255) DEFAULT NULL COMMENT '注册管理员',
  `EXT4` varchar(255) DEFAULT NULL COMMENT '注册管理员密码',
  `EMAIL` varchar(255) DEFAULT NULL COMMENT '公司邮箱',
  `PHONE` varchar(30) DEFAULT NULL COMMENT '公司电话',
  `WEBSITE` varchar(255) DEFAULT NULL COMMENT '公司网站',
  `ACCREDIT` decimal(65,0) DEFAULT NULL COMMENT '是否已进行授权'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `ecoperatorbasicsettings` (
  `pk` varchar(32) NOT NULL,
  `companypk` varchar(255) DEFAULT NULL,
  `deleteip` varchar(255) DEFAULT NULL,
  `deletepk` varchar(255) DEFAULT NULL,
  `deletetime` datetime DEFAULT NULL,
  `insertip` varchar(255) DEFAULT NULL,
  `insertpk` varchar(255) DEFAULT NULL,
  `inserttime` datetime DEFAULT NULL,
  `isdelete` int(11) DEFAULT NULL,
  `updateip` varchar(255) DEFAULT NULL,
  `updatepk` varchar(255) DEFAULT NULL,
  `updatetime` datetime DEFAULT NULL,
  `version` bigint(20) NOT NULL,
  `customerbusy` int(11) DEFAULT NULL,
  `customerfrovisitors` int(11) DEFAULT NULL,
  `customertimout` int(11) DEFAULT NULL,
  `initiativetimeout` int(11) DEFAULT NULL,
  `membersleave` int(11) DEFAULT NULL,
  `noresponse` int(11) DEFAULT NULL,
  `operationtimeout` int(11) DEFAULT NULL,
  `overtime` int(11) DEFAULT NULL,
  `userpks` varchar(255) DEFAULT NULL,
  `mediachatrqtimeout` bigint(20) DEFAULT '0',
  `isNeedDialogueClassification` int(11) DEFAULT '2',
  `isNeedVisitorInBeep` int(11) DEFAULT '2',
  `threshold` int(3) DEFAULT '0',
  `isNeedRevoke` int(11) DEFAULT '2',
  `revoketime` int(11) DEFAULT '120',
  `isDisplayWelcomePage` int(11) DEFAULT '1',
  `ISNEEDRECOMMOND` int(11) DEFAULT '2',
  PRIMARY KEY (`pk`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `ecchatreportupdate` (
  `COMPANY_PK` varchar(32) COLLATE utf8_bin NOT NULL,
  `TIME` datetime DEFAULT NULL,
  `TOTAL` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
